name: Build Dark Notepad EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "DarkNotepad" dark_notepad.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DarkNotepad-Windows
        path: dist/DarkNotepad.exe
        retention-days: 30
